# Generated by Django 5.2 on 2026-02-24 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時刻')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='練習時間（分）')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='評価')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('is_quick_record', models.BooleanField(default=False, verbose_name='クイック記録')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='曲名')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='アーティスト')),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='難易度')),
                ('status', models.CharField(choices=[('practicing', '練習中'), ('can_play', '弾ける'), ('rest', 'お休み')], default='practicing', max_length=20, verbose_name='ステータス')),
                ('target_bpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='目標BPM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='練習時間（分）')),
                ('bpm_achieved', models.PositiveIntegerField(blank=True, null=True, verbose_name='達成BPM')),
                ('practice_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_entries', to='guitarlog.practicesong')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_songs', to='guitarlog.practicesession')),
            ],
        ),
    ]
