# Generated by Django 5.2 on 2026-02-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarlog', '0002_practicegoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesong',
            name='album_art_url',
            field=models.URLField(blank=True, verbose_name='アルバムアート'),
        ),
        migrations.AddField(
            model_name='practicesong',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Spotify ID'),
        ),
    ]
