# Generated by Django 5.2 on 2026-02-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200, verbose_name='アーティスト')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='公演名')),
                ('date', models.DateField(verbose_name='公演日')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='会場')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='感想')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='評価')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impression', to='livelog.liveevent')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='金額')),
                ('category', models.CharField(choices=[('ticket', 'チケット'), ('transport', '交通費'), ('goods', 'グッズ'), ('food', '飲食'), ('accommodation', '宿泊'), ('other', 'その他')], max_length=20, verbose_name='カテゴリ')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
                ('date', models.DateField(verbose_name='日付')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_expenses', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='livelog.liveevent')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SetlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=200, verbose_name='曲名')),
                ('order', models.PositiveIntegerField(verbose_name='順番')),
                ('song_type', models.CharField(choices=[('normal', '通常'), ('encore', 'アンコール'), ('double_encore', 'ダブルアンコール')], default='normal', max_length=20, verbose_name='種別')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist', to='livelog.liveevent')),
            ],
            options={
                'ordering': ['event', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('standing', 'スタンディング'), ('reserved', '指定席'), ('arena', 'アリーナ'), ('vip', 'VIP'), ('other', 'その他')], default='reserved', max_length=20, verbose_name='チケット種別')),
                ('seat_info', models.CharField(blank=True, max_length=100, verbose_name='座席情報')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='チケット価格')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='livelog.liveevent')),
            ],
        ),
    ]
