# Generated by Django 5.2 on 2026-02-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='livelog/thumbnails/', verbose_name='サムネイル'),
        ),
    ]
