# Generated by Django 5.2 on 2026-02-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livelog', '0002_liveevent_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='artist_image_url',
            field=models.URLField(blank=True, verbose_name='アーティスト画像'),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='spotify_artist_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Spotify Artist ID'),
        ),
    ]
