# Generated by Django 5.2 on 2026-02-25 16:12

import uuid
from django.db import migrations


def populate_tokens(apps, schema_editor):
    LiveEvent = apps.get_model('livelog', 'LiveEvent')
    for event in LiveEvent.objects.filter(share_token__isnull=True):
        event.share_token = uuid.uuid4()
        event.save(update_fields=['share_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('livelog', '0004_liveevent_share_token'),
    ]

    operations = [
        migrations.RunPython(populate_tokens, migrations.RunPython.noop),
    ]
