# Generated by Django 5.2 on 2026-02-25 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False, verbose_name='プロフィールを公開')),
                ('show_practice_stats', models.BooleanField(default=True, verbose_name='練習統計を表示')),
                ('show_live_history', models.BooleanField(default=True, verbose_name='ライブ履歴を表示')),
                ('show_compositions', models.BooleanField(default=True, verbose_name='作曲プロジェクトを表示')),
                ('show_achievements', models.BooleanField(default=True, verbose_name='実績を表示')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='自己紹介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プロフィール設定',
                'verbose_name_plural': 'プロフィール設定',
            },
        ),
    ]
