# Generated by Django 5.2 on 2026-02-24 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='トピック名')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('category', models.CharField(choices=[('scale', '音階'), ('chord', '和音'), ('progression', 'コード進行'), ('interval', '音程'), ('key', '調'), ('rhythm', 'リズム'), ('form', '楽曲形式'), ('technique', 'テクニック')], max_length=20, verbose_name='カテゴリ')),
                ('difficulty', models.IntegerField(choices=[(1, '初級'), (2, '初中級'), (3, '中級'), (4, '中上級'), (5, '上級')], default=3, verbose_name='難易度')),
                ('summary', models.TextField(verbose_name='概要')),
                ('body', models.TextField(verbose_name='本文')),
                ('tags', models.CharField(blank=True, help_text='カンマ区切りのキーワード', max_length=500, verbose_name='タグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_topics', models.ManyToManyField(blank=True, to='music_theory.topic', verbose_name='関連トピック')),
            ],
            options={
                'verbose_name': '音楽理論トピック',
                'verbose_name_plural': '音楽理論トピック',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='music_theory.topic')),
            ],
            options={
                'verbose_name': 'ブックマーク',
                'verbose_name_plural': 'ブックマーク',
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
