# Generated by Django 5.2 on 2026-02-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_theory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('scale', '音階'), ('chord', '和音'), ('progression', 'コード進行'), ('interval', '音程'), ('key', '調'), ('rhythm', 'リズム'), ('form', '楽曲形式')], max_length=20, verbose_name='カテゴリ'),
        ),
    ]
