# Generated by Django 5.2 on 2026-02-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_theory', '0002_alter_topic_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChordProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='進行名')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('starting_chord', models.CharField(choices=[('I', 'I 始まり'), ('IIm', 'IIm 始まり'), ('IIIm', 'IIIm 始まり'), ('IV', 'IV 始まり'), ('V', 'V 始まり'), ('VIm', 'VIm 始まり')], max_length=10, verbose_name='開始コード')),
                ('degrees', models.CharField(max_length=200, verbose_name='ディグリー')),
                ('chords_in_c', models.CharField(max_length=200, verbose_name='Cキーのコード')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='タグ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'コード進行',
                'verbose_name_plural': 'コード進行',
                'ordering': ['starting_chord', 'order'],
            },
        ),
    ]
