# Generated by Django 5.2 on 2026-02-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_theory', '0005_topicprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicProgress',
        ),
    ]
