from django.core.management.base import BaseCommand
from music_theory.models import ChordProgression

SEED_DATA = [
    # === I 始まり ===
    {
        'name': 'カノン進行',
        'slug': 'canon',
        'starting_chord': 'I',
        'degrees': 'I → V → VIm → IIIm → IV → I → IV → V',
        'chords_in_c': 'C → G → Am → Em → F → C → F → G',
        'description': 'パッヘルベルのカノンに由来。J-POPで最も多用される進行の一つ。',
        'tags': 'カノン,パッヘルベル,定番,J-POP',
        'order': 1,
    },
    {
        'name': '王道進行',
        'slug': 'oudou',
        'starting_chord': 'I',
        'degrees': 'I → V → VIm → IV',
        'chords_in_c': 'C → G → Am → F',
        'description': '洋楽・J-POP問わず世界中で使われる定番進行。',
        'tags': '王道,定番,ポップス',
        'order': 2,
    },
    {
        'name': '丸サ進行（丸の内サディスティック進行）',
        'slug': 'marusa',
        'starting_chord': 'I',
        'degrees': 'IM7 → III7 → VIm7 → I7 → IVM7',
        'chords_in_c': 'CM7 → E7 → Am7 → C7 → FM7',
        'description': '椎名林檎「丸の内サディスティック」由来。おしゃれな響きが特徴。',
        'tags': '丸サ,椎名林檎,おしゃれ,セカンダリードミナント',
        'order': 3,
    },
    {
        'name': 'I → IV → V → I（基本形）',
        'slug': 'basic-i-iv-v-i',
        'starting_chord': 'I',
        'degrees': 'I → IV → V → I',
        'chords_in_c': 'C → F → G → C',
        'description': '最も基本的なコード進行。トニック→サブドミナント→ドミナント→トニック。',
        'tags': '基本,入門,T-SD-D-T',
        'order': 4,
    },
    {
        'name': 'I → VIm → IV → V',
        'slug': 'i-vim-iv-v',
        'starting_chord': 'I',
        'degrees': 'I → VIm → IV → V',
        'chords_in_c': 'C → Am → F → G',
        'description': '50年代進行の変形。明るく前向きな響き。',
        'tags': '50年代,ポップス,明るい',
        'order': 5,
    },
    {
        'name': 'I → VIm → IIm → V（50年代進行）',
        'slug': 'fifties',
        'starting_chord': 'I',
        'degrees': 'I → VIm → IIm → V',
        'chords_in_c': 'C → Am → Dm → G',
        'description': '1950年代のポップスで多用された循環コード。',
        'tags': '50年代,循環コード,オールディーズ',
        'order': 6,
    },
    {
        'name': 'I → III7 → VIm → V',
        'slug': 'i-iii7-vim-v',
        'starting_chord': 'I',
        'degrees': 'I → III7 → VIm → V',
        'chords_in_c': 'C → E7 → Am → G',
        'description': 'III7（セカンダリードミナント）でVImへ強く解決する進行。',
        'tags': 'セカンダリードミナント,ドラマチック',
        'order': 7,
    },
    {
        'name': 'I → ♭VII → IV → I',
        'slug': 'i-bvii-iv-i',
        'starting_chord': 'I',
        'degrees': 'I → ♭VII → IV → I',
        'chords_in_c': 'C → Bb → F → C',
        'description': 'ロックで頻出。♭VIIはミクソリディアンモードからの借用。',
        'tags': 'ロック,モーダルインターチェンジ,ミクソリディアン',
        'order': 8,
    },
    {
        'name': 'I → IV → VIm → V',
        'slug': 'i-iv-vim-v',
        'starting_chord': 'I',
        'degrees': 'I → IV → VIm → V',
        'chords_in_c': 'C → F → Am → G',
        'description': '明るさと切なさが共存する進行。',
        'tags': 'ポップス,バラード',
        'order': 9,
    },
    {
        'name': 'I → V/VIm → VIm → V',
        'slug': 'i-v-of-vim-vim-v',
        'starting_chord': 'I',
        'degrees': 'I → III7 → VIm → V',
        'chords_in_c': 'C → E7 → Am → G',
        'description': 'セカンダリードミナント（V/VIm = III7）を使った進行。',
        'tags': 'セカンダリードミナント',
        'order': 10,
    },
    {
        'name': 'I → ♭III → IV → I',
        'slug': 'i-biii-iv-i',
        'starting_chord': 'I',
        'degrees': 'I → ♭III → IV → I',
        'chords_in_c': 'C → Eb → F → C',
        'description': '♭IIIの借用コードを使ったロック系進行。',
        'tags': 'ロック,モーダルインターチェンジ',
        'order': 11,
    },
    {
        'name': 'I → V → ♭VII → IV',
        'slug': 'i-v-bvii-iv',
        'starting_chord': 'I',
        'degrees': 'I → V → ♭VII → IV',
        'chords_in_c': 'C → G → Bb → F',
        'description': 'ロック定番。♭VIIがアクセント。',
        'tags': 'ロック,定番',
        'order': 12,
    },
    {
        'name': 'I → IV → I → V',
        'slug': 'i-iv-i-v',
        'starting_chord': 'I',
        'degrees': 'I → IV → I → V',
        'chords_in_c': 'C → F → C → G',
        'description': 'シンプルな3コード進行。フォーク・カントリーで定番。',
        'tags': '3コード,フォーク,カントリー,シンプル',
        'order': 13,
    },
    {
        'name': 'I → IIm7 → IIIm7 → IV',
        'slug': 'i-iim7-iiim7-iv',
        'starting_chord': 'I',
        'degrees': 'I → IIm7 → IIIm7 → IV',
        'chords_in_c': 'C → Dm7 → Em7 → F',
        'description': '順次上行する美しい進行。クリシェ的な動き。',
        'tags': '上行,クリシェ,美しい',
        'order': 14,
    },
    {
        'name': 'I → I7 → IV → IVm',
        'slug': 'i-i7-iv-ivm',
        'starting_chord': 'I',
        'degrees': 'I → I7 → IV → IVm',
        'chords_in_c': 'C → C7 → F → Fm',
        'description': 'I7→IVでセカンダリードミナント、IVm（サブドミナントマイナー）で切ない響きに。',
        'tags': 'サブドミナントマイナー,切ない,ビートルズ',
        'order': 15,
    },
    {
        'name': 'I → ♭VI → ♭VII → I',
        'slug': 'i-bvi-bvii-i',
        'starting_chord': 'I',
        'degrees': 'I → ♭VI → ♭VII → I',
        'chords_in_c': 'C → Ab → Bb → C',
        'description': 'モーダルインターチェンジ（同主調借用）を使ったロック進行。',
        'tags': 'モーダルインターチェンジ,ロック,同主調借用',
        'order': 16,
    },
    {
        'name': 'I → IVm → I（サブドミナントマイナー）',
        'slug': 'i-ivm-i',
        'starting_chord': 'I',
        'degrees': 'I → IVm → I',
        'chords_in_c': 'C → Fm → C',
        'description': 'サブドミナントマイナーの基本形。切ない解決感。',
        'tags': 'サブドミナントマイナー,切ない,同主調借用',
        'order': 17,
    },
    {
        'name': 'I → V → VIm → IIIm → IV → I → IIm → V',
        'slug': 'canon-extended',
        'starting_chord': 'I',
        'degrees': 'I → V → VIm → IIIm → IV → I → IIm → V',
        'chords_in_c': 'C → G → Am → Em → F → C → Dm → G',
        'description': 'カノン進行のIIm変形版。より自然なベースライン。',
        'tags': 'カノン,変形,ベースライン',
        'order': 18,
    },
    {
        'name': 'I → V → VIm → IV → I → V → IIIm → IV',
        'slug': 'oudou-extended',
        'starting_chord': 'I',
        'degrees': 'I → V → VIm → IV → I → V → IIIm → IV',
        'chords_in_c': 'C → G → Am → F → C → G → Em → F',
        'description': '王道進行を2周させた8小節パターン。',
        'tags': '王道,8小節,展開',
        'order': 19,
    },
    {
        'name': 'I → IM7 → I7 → IV',
        'slug': 'chromatic-descent-i',
        'starting_chord': 'I',
        'degrees': 'I → IM7 → I7 → IV',
        'chords_in_c': 'C → CM7 → C7 → F',
        'description': 'トップノートが半音下行するクリシェ。内声の動きが美しい。',
        'tags': 'クリシェ,半音下行,内声',
        'order': 20,
    },

    # === IIm 始まり ===
    {
        'name': 'ツーファイブワン（II-V-I）',
        'slug': 'two-five-one',
        'starting_chord': 'IIm',
        'degrees': 'IIm7 → V7 → IM7',
        'chords_in_c': 'Dm7 → G7 → CM7',
        'description': 'ジャズの最重要進行。SD→D→Tの最も強い解決。',
        'tags': 'ジャズ,ツーファイブワン,II-V-I,基本',
        'order': 1,
    },
    {
        'name': 'IIm → V → I → VIm',
        'slug': 'iim-v-i-vim',
        'starting_chord': 'IIm',
        'degrees': 'IIm → V → I → VIm',
        'chords_in_c': 'Dm → G → C → Am',
        'description': 'II-V-Iにトニック代理VImを加えた循環型。',
        'tags': 'ツーファイブワン,循環',
        'order': 2,
    },
    {
        'name': 'IIm → V → IIIm → VIm',
        'slug': 'iim-v-iiim-vim',
        'starting_chord': 'IIm',
        'degrees': 'IIm → V → IIIm → VIm',
        'chords_in_c': 'Dm → G → Em → Am',
        'description': 'トニック代理（IIIm, VIm）への解決。偽終止的な響き。',
        'tags': '偽終止,裏切り',
        'order': 3,
    },
    {
        'name': 'IIm → V → I → IV',
        'slug': 'iim-v-i-iv',
        'starting_chord': 'IIm',
        'degrees': 'IIm → V → I → IV',
        'chords_in_c': 'Dm → G → C → F',
        'description': 'II-V-I後にIVで展開する進行。',
        'tags': 'ツーファイブワン,展開',
        'order': 4,
    },
    {
        'name': 'IIm7 → V7 → IM7 → IV7',
        'slug': 'iim7-v7-im7-iv7',
        'starting_chord': 'IIm',
        'degrees': 'IIm7 → V7 → IM7 → IVM7',
        'chords_in_c': 'Dm7 → G7 → CM7 → FM7',
        'description': 'ジャズバラードの定番。四和音による洗練された響き。',
        'tags': 'ジャズ,四和音,洗練',
        'order': 5,
    },
    {
        'name': 'IIm7 → ♭II7 → IM7（裏コード）',
        'slug': 'tritone-sub',
        'starting_chord': 'IIm',
        'degrees': 'IIm7 → ♭II7 → IM7',
        'chords_in_c': 'Dm7 → Db7 → CM7',
        'description': 'V7の代わりに♭II7（トライトーン代理）を使用。半音下行のベースライン。',
        'tags': '裏コード,トライトーン代理,ジャズ,半音下行',
        'order': 6,
    },
    {
        'name': 'IIm → IIm/V → V → I',
        'slug': 'iim-iim-on-v-v-i',
        'starting_chord': 'IIm',
        'degrees': 'IIm → IIm/V → V → I',
        'chords_in_c': 'Dm → Dm/G → G → C',
        'description': 'ベースラインがスムーズに下行するツーファイブワン変形。',
        'tags': 'オンコード,ベースライン,ツーファイブワン',
        'order': 7,
    },

    # === IIIm 始まり ===
    {
        'name': 'IIIm → IV → V → I',
        'slug': 'iiim-iv-v-i',
        'starting_chord': 'IIIm',
        'degrees': 'IIIm → IV → V → I',
        'chords_in_c': 'Em → F → G → C',
        'description': 'IIImから順次上行してIへ解決。力強い上昇感。',
        'tags': '上行,解決,力強い',
        'order': 1,
    },
    {
        'name': 'IIIm → VIm → IIm → V',
        'slug': 'iiim-vim-iim-v',
        'starting_chord': 'IIIm',
        'degrees': 'IIIm → VIm → IIm → V',
        'chords_in_c': 'Em → Am → Dm → G',
        'description': '5度圏に沿った下降進行。自然で滑らかな流れ。',
        'tags': '5度圏,下降,自然',
        'order': 2,
    },

    # === IV 始まり ===
    {
        'name': '逆王道進行',
        'slug': 'reverse-oudou',
        'starting_chord': 'IV',
        'degrees': 'IV → V → IIIm → VIm',
        'chords_in_c': 'F → G → Em → Am',
        'description': '王道進行(I→V→VIm→IV)を逆にした進行。J-POPのサビで多用。',
        'tags': '逆王道,J-POP,サビ,定番',
        'order': 1,
    },
    {
        'name': 'Just The Two Of Us進行',
        'slug': 'just-the-two-of-us',
        'starting_chord': 'IV',
        'degrees': 'IVM7 → III7 → VIm7 → VIm7',
        'chords_in_c': 'FM7 → E7 → Am7 → Am7',
        'description': 'Grover Washington Jr.の名曲由来。シティポップ・R&Bの定番。',
        'tags': 'シティポップ,R&B,おしゃれ,定番',
        'order': 2,
    },
    {
        'name': 'IV → I → V → VIm',
        'slug': 'iv-i-v-vim',
        'starting_chord': 'IV',
        'degrees': 'IV → I → V → VIm',
        'chords_in_c': 'F → C → G → Am',
        'description': 'サブドミナント始まりの明るい進行。',
        'tags': 'ポップス,明るい',
        'order': 3,
    },
    {
        'name': 'IV → V → VIm → I',
        'slug': 'iv-v-vim-i',
        'starting_chord': 'IV',
        'degrees': 'IV → V → VIm → I',
        'chords_in_c': 'F → G → Am → C',
        'description': 'サブドミナントから上昇していく進行。',
        'tags': '上行,展開',
        'order': 4,
    },
    {
        'name': 'IV → IVm → I（サブドミナントマイナー終止）',
        'slug': 'iv-ivm-i',
        'starting_chord': 'IV',
        'degrees': 'IV → IVm → I',
        'chords_in_c': 'F → Fm → C',
        'description': 'IV→IVm→Iの切ない終止。エンディングで多用。',
        'tags': 'サブドミナントマイナー,終止,切ない,エンディング',
        'order': 5,
    },
    {
        'name': 'IV → V → I → I',
        'slug': 'iv-v-i-i',
        'starting_chord': 'IV',
        'degrees': 'IV → V → I → I',
        'chords_in_c': 'F → G → C → C',
        'description': 'シンプルなSD→D→T進行。サビの締めくくりに。',
        'tags': 'シンプル,終止,サビ',
        'order': 6,
    },
    {
        'name': 'IV → V → IIIm → VIm → IIm → V → I',
        'slug': 'reverse-oudou-extended',
        'starting_chord': 'IV',
        'degrees': 'IV → V → IIIm → VIm → IIm → V → I',
        'chords_in_c': 'F → G → Em → Am → Dm → G → C',
        'description': '逆王道進行からII-V-Iで解決する展開型。',
        'tags': '逆王道,展開,ツーファイブワン',
        'order': 7,
    },
    {
        'name': 'IV → ♭VII → I',
        'slug': 'iv-bvii-i',
        'starting_chord': 'IV',
        'degrees': 'IV → ♭VII → I',
        'chords_in_c': 'F → Bb → C',
        'description': '♭VIIを経由する解決。ロック・ブルース的な響き。',
        'tags': 'ロック,ブルース,モーダルインターチェンジ',
        'order': 8,
    },
    {
        'name': 'IVM7 → IIIm7 → IIm7 → IM7',
        'slug': 'descending-diatonic',
        'starting_chord': 'IV',
        'degrees': 'IVM7 → IIIm7 → IIm7 → IM7',
        'chords_in_c': 'FM7 → Em7 → Dm7 → CM7',
        'description': '順次下行するダイアトニック進行。美しい流れ。',
        'tags': '下行,ダイアトニック,美しい,四和音',
        'order': 9,
    },
    {
        'name': 'IV → V → IIIm7 → VIm → IV → V → I',
        'slug': 'iv-v-iiim7-vim-iv-v-i',
        'starting_chord': 'IV',
        'degrees': 'IV → V → IIIm7 → VIm → IV → V → I',
        'chords_in_c': 'F → G → Em7 → Am → F → G → C',
        'description': '逆王道進行からIV→V→Iで解決する8小節展開。',
        'tags': '逆王道,8小節,J-POP',
        'order': 10,
    },

    # === V 始まり ===
    {
        'name': 'V → IV → I（ロックケーデンス）',
        'slug': 'rock-cadence',
        'starting_chord': 'V',
        'degrees': 'V → IV → I',
        'chords_in_c': 'G → F → C',
        'description': 'ドミナントからサブドミナント経由で解決。ロックの定番終止。',
        'tags': 'ロック,終止,逆進行',
        'order': 1,
    },
    {
        'name': 'V → VIm → IV → I',
        'slug': 'v-vim-iv-i',
        'starting_chord': 'V',
        'degrees': 'V → VIm → IV → I',
        'chords_in_c': 'G → Am → F → C',
        'description': 'ドミナントからの偽終止を経てIへ解決。',
        'tags': '偽終止,展開',
        'order': 2,
    },

    # === VIm 始まり ===
    {
        'name': '小室進行',
        'slug': 'komuro',
        'starting_chord': 'VIm',
        'degrees': 'VIm → IV → V → I',
        'chords_in_c': 'Am → F → G → C',
        'description': '小室哲哉プロデュース曲で多用。90年代J-POPの代名詞。',
        'tags': '小室哲哉,90年代,J-POP,定番',
        'order': 1,
    },
    {
        'name': 'VIm → IV → I → V',
        'slug': 'vim-iv-i-v',
        'starting_chord': 'VIm',
        'degrees': 'VIm → IV → I → V',
        'chords_in_c': 'Am → F → C → G',
        'description': 'マイナーから始まる循環進行。Let It Be等で有名。',
        'tags': 'Let It Be,循環,マイナー始まり',
        'order': 2,
    },
    {
        'name': 'VIm → V → IV → V',
        'slug': 'vim-v-iv-v',
        'starting_chord': 'VIm',
        'degrees': 'VIm → V → IV → V',
        'chords_in_c': 'Am → G → F → G',
        'description': 'マイナーから始まる切ない進行。Aメロで多用。',
        'tags': '切ない,Aメロ',
        'order': 3,
    },
    {
        'name': 'VIm → IIIm → IV → I',
        'slug': 'vim-iiim-iv-i',
        'starting_chord': 'VIm',
        'degrees': 'VIm → IIIm → IV → I',
        'chords_in_c': 'Am → Em → F → C',
        'description': 'マイナーからメジャーへ展開する進行。',
        'tags': 'マイナー始まり,展開',
        'order': 4,
    },
    {
        'name': 'VIm → V → IIIm → IV',
        'slug': 'vim-v-iiim-iv',
        'starting_chord': 'VIm',
        'degrees': 'VIm → V → IIIm → IV',
        'chords_in_c': 'Am → G → Em → F',
        'description': 'マイナー始まりでIIImを経由する進行。',
        'tags': 'マイナー始まり,IIIm経由',
        'order': 5,
    },
    {
        'name': 'VIm → V → IV → IIIm（アンダルシア終止）',
        'slug': 'andalusian-cadence',
        'starting_chord': 'VIm',
        'degrees': 'VIm → V → IV → IIIm',
        'chords_in_c': 'Am → G → F → Em',
        'description': 'フラメンコ由来の下行進行。ラメンテーション・バスとも呼ばれる。',
        'tags': 'アンダルシア,フラメンコ,下行,ラメンテーション',
        'order': 6,
    },
]


class Command(BaseCommand):
    help = 'コード進行のシードデータを投入'

    def handle(self, *args, **options):
        seed_slugs = {d['slug'] for d in SEED_DATA}

        deleted_count, _ = ChordProgression.objects.exclude(slug__in=seed_slugs).delete()
        if deleted_count:
            self.stdout.write(self.style.WARNING(f'  削除: {deleted_count} 件'))

        created = 0
        updated = 0
        for data in SEED_DATA:
            slug = data['slug']
            defaults = {k: v for k, v in data.items() if k != 'slug'}
            _, was_created = ChordProgression.objects.update_or_create(
                slug=slug,
                defaults=defaults,
            )
            if was_created:
                created += 1
            else:
                updated += 1

        total = ChordProgression.objects.count()
        self.stdout.write(self.style.SUCCESS(
            f'完了: 新規 {created} 件 / 更新 {updated} 件 / 合計 {total} 件'
        ))
