# Generated by Django 5.2 on 2026-02-24 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='曲名')),
                ('title_kana', models.CharField(blank=True, max_length=200, verbose_name='曲名（かな）')),
                ('artist', models.CharField(max_length=200, verbose_name='アーティスト')),
                ('artist_kana', models.CharField(blank=True, max_length=200, verbose_name='アーティスト（かな）')),
                ('original_key', models.CharField(default='C', max_length=10, verbose_name='キー')),
                ('bpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM')),
                ('difficulty', models.IntegerField(choices=[(1, '初級'), (2, '初中級'), (3, '中級'), (4, '中上級'), (5, '上級')], default=3, verbose_name='難易度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['artist', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChordSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('intro', 'イントロ'), ('verse', 'Aメロ'), ('verse2', 'Bメロ'), ('chorus', 'サビ'), ('bridge', 'Cメロ'), ('interlude', '間奏'), ('outro', 'アウトロ')], max_length=20, verbose_name='セクション')),
                ('order', models.PositiveIntegerField(verbose_name='表示順')),
                ('bar_count', models.PositiveIntegerField(default=4, verbose_name='小節数')),
                ('chords', models.JSONField(help_text='例: [["C","","Am",""],["F","G","C",""]]', verbose_name='コード進行')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='jpop_chord.song')),
            ],
            options={
                'ordering': ['song', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capo_setting', models.IntegerField(default=0, verbose_name='カポ位置')),
                ('key_offset', models.IntegerField(default=0, verbose_name='キーオフセット')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='jpop_chord.song')),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
    ]
