# Generated by Django 5.2 on 2026-02-24 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('status', models.CharField(choices=[('idea', 'アイデア'), ('sketch', 'スケッチ'), ('composing', '作曲中'), ('arranging', '編曲中'), ('lyrics', '作詞中'), ('recording', 'レコーディング'), ('done', '完成')], default='idea', max_length=20, verbose_name='ステータス')),
                ('key', models.CharField(blank=True, max_length=10, verbose_name='キー')),
                ('bpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM')),
                ('tags', models.CharField(blank=True, help_text='カンマ区切り', max_length=200, verbose_name='タグ')),
                ('description', models.TextField(blank=True, verbose_name='概要')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compose_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_type', models.CharField(choices=[('text', 'テキスト'), ('audio', '音声'), ('photo', '写真')], default='text', max_length=10, verbose_name='種類')),
                ('text_content', models.TextField(blank=True, verbose_name='テキスト')),
                ('audio_file', models.FileField(blank=True, upload_to='songdiary/audio/', verbose_name='音声ファイル')),
                ('photo_file', models.ImageField(blank=True, upload_to='songdiary/photos/', verbose_name='写真')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='songdiary.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
