# Generated by Django 5.2 on 2026-02-25 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='share_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='共有トークン'),
        ),
    ]
