# Generated by Django 5.2 on 2026-02-25 16:12

import uuid
from django.db import migrations


def populate_tokens(apps, schema_editor):
    Project = apps.get_model('songdiary', 'Project')
    for project in Project.objects.filter(share_token__isnull=True):
        project.share_token = uuid.uuid4()
        project.save(update_fields=['share_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('songdiary', '0002_project_share_token'),
    ]

    operations = [
        migrations.RunPython(populate_tokens, migrations.RunPython.noop),
    ]
