# Generated by Django 5.2 on 2026-02-25 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdiary', '0003_populate_share_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='共有トークン'),
        ),
    ]
